"use client";

import { Calendar, ShieldCheck, FileText, DollarSign, Activity, Wallet, Percent } from "lucide-react";
import { ScoreGauge } from "@/components/dashboard/ScoreGauge";
import { MetricCard } from "@/components/dashboard/MetricCard";
import { RiskDonutChart } from "@/components/dashboard/RiskDonutChart";
import { InsightsPanel } from "@/components/dashboard/InsightsPanel";
import { XAIBarChart } from "@/components/dashboard/XAIBarChart";
import { useSettings } from "@/context/SettingsContext";
import { formatCurrency } from "@/lib/format";

export function ReportTemplate({ report, reportRef }) {
  const { currency } = useSettings();

  if (!report) return null;

  return (
    <div 
      id="report-content" 
      ref={reportRef}
      className="bg-white dark:bg-[#0B0F1A] border border-gray-100 dark:border-white/5 rounded-3xl p-8 sm:p-12 shadow-2xl relative overflow-hidden"
    >
      {/* PDF Header Decoration */}
      <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 blur-3xl rounded-full -mr-20 -mt-20 pointer-events-none" />
      
      {/* Identification Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center border-b border-gray-100 dark:border-white/10 pb-8 mb-12 gap-6 relative z-10">
        <div className="flex items-center space-x-4">
          <div className="p-3 bg-neon-blue/10 border border-neon-blue/20 rounded-2xl text-neon-blue">
            <FileText className="w-8 h-8" />
          </div>
          <div>
            <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">{report.company}</h1>
            <div className="flex items-center space-x-4 mt-1 text-sm text-slate-500 dark:text-muted-foreground font-medium">
              <span className="flex items-center"><Calendar className="w-3.5 h-3.5 mr-1.5" /> {report.date}</span>
              <span className="flex items-center"><ShieldCheck className="w-3.5 h-3.5 mr-1.5" /> ID: {report.id}</span>
            </div>
          </div>
        </div>
        
        <div className="flex flex-col items-end">
           <div className="px-4 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-bold uppercase tracking-widest mb-1">
             {report.status}
           </div>
           <p className="text-[10px] text-slate-400 dark:text-muted-foreground uppercase tracking-tighter">Generated by CredMetric AI v2.4</p>
        </div>
      </div>

      {/* Report Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
         {/* Section 1: Core Health */}
         <div className="lg:col-span-4 space-y-8">
            <div className="h-72">
              <ScoreGauge 
                score={report.score} 
                riskLevel={`${report.risk} Risk`}
                subtext="Overall health score"
              />
            </div>
            <div className="h-80">
              <RiskDonutChart />
            </div>
         </div>

         {/* Section 2: Financial Performance & Drivers */}
         <div className="lg:col-span-8 space-y-8">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
               <MetricCard title="Revenue" value={formatCurrency(report.metrics.revenue, currency, true)} change="+12%" trend="up" Icon={DollarSign} />
               <MetricCard title="Net Profit" value={formatCurrency(report.metrics.profit, currency, true)} change="+5%" trend="up" Icon={Activity} />
               <MetricCard title="Debt-to-Eq" value={report.metrics.debtToEq} change="-2%" trend="down" Icon={Wallet} />
               <MetricCard title="Liquidity" value={report.metrics.liquidity} change="+8%" trend="up" Icon={Percent} />
            </div>
            
            <div className="min-h-[350px]">
              <XAIBarChart />
            </div>

            <div className="min-h-[300px]">
              <InsightsPanel />
            </div>
         </div>
      </div>

      {/* Footer Disclaimer */}
      <div className="mt-16 pt-8 border-t border-gray-100 dark:border-white/5 text-center">
        <p className="text-xs text-slate-400 dark:text-muted-foreground leading-relaxed max-w-2xl mx-auto">
          This report is generated by the CredMetric AI engine based on the financial documents uploaded for analysis. 
          Projections are probabilistic estimates. Confidential and proprietary information for external decision support.
        </p>
      </div>
    </div>
  );
}
